@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as User
participant ":Vote1" as vote1
participant ":Vote2" as vote2

activate User

User -> vote1: GET/votes/{reviewId}/{userId}
vote1 -> vote2: GET/8085/votes/{reviewId}/{userId}
vote2 --> vote1: Vote
vote1 --> User: Vote
@enduml